language: python
python:
    - "3.6"

services:
    - docker

install:
    - pip install flake8
    - docker build . -t tf2_baselines-test

script:
    - flake8 . --show-source --statistics
    - docker run -e RUNSLOW=1 tf2_baselines-test pytest -v .
